BOLD_ACTIVATE = 'activate-bold'
BOLD_DEACTIVATE = 'deactivate-bold'
ITALIC_ACTIVATE = 'activate-italic'
ITALIC_DEACTIVATE = 'deactivate-italic'
UNDERLINE_ACTIVATE = 'activate-underline'
UNDERLINE_DEACTIVATE = 'deactivate-underline'
FONT_CHANGE = 'cursor-font-changed'
SIZE_CHANGE = 'cursor-size-changed'
