# FileToolbar signals
NEW_FILE = 'new-file'
OPEN_FILE = 'open-file'
SAVE_FILE = 'save-file'
SAVE_FILE_AS = 'save-file-as'
COPY_BBCODE = 'copy-bbcode'
UNDO = 'undo-action'
REDO = 'redo-action'
QUIT = 'toolbar-quit'

# FormattingToolbar signals
BOLD_ACTIVE = 'bold-active'
BOLD_INACTIVE = 'bold-inactive'
ITALIC_ACTIVE = 'italic-active'
ITALIC_INACTIVE = 'italic-inactive'
UNDERLINE_ACTIVE = 'underline-active'
UNDERLINE_INACTIVE = 'underline-inactive'
FAMILY_CHANGE = 'change-font-family'
SIZE_CHANGE = 'change-font-size'
